name: Docker

on:
    push:
        branches:
            - "main"
        tags:
            - "*"
    workflow_dispatch:

jobs:
    publish_bot:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Docker meta
              id: meta
              uses: docker/metadata-action@v4
              with:
                  # list of Docker images to use as base name for tags
                  images: ghcr.io/blackdemonfire/snowglow
                  # generate Docker tags based on branch and short commit SHA
                  tags: |
                      type=ref,event=branch
                      type=sha
                  flavor: |
                      latest=auto
                      prefix=
                      suffix=
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2
            - name: Login to DockerHub
              uses: docker/login-action@v2
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: Build and push - Bot
              uses: docker/build-push-action@v3
              with:
                  push: ${{ github.event_name != 'pull_request' }}
                  tags: blackdemonfire/snowglow:latest

